#!/bin/bash

ARTIFACTS_HOME="${HOME}/ksplit-artifacts"
MSR_ARTIFACT="${ARTIFACTS_HOME}/msr"
MSR_BOILERPLATE="${MSR_ARTIFACT}/msr_autogen"

BASE_DIR="/opt/ksplit"
BCFILES="${BASE_DIR}/bc-files"
MSR_BC="${BCFILES}/arch_x86/msr/"

BFLANK_BUILD="${BASE_DIR}/bflank/build"

LVD_LINUX="${BASE_DIR}/lvd-linux"
LVD_DOMAINS="${LVD_LINUX}/lcd-domains"
TEST_MODS="${LVD_DOMAINS}/test_mods"

MSR_AUTOGEN_BUILD_DIR="${LVD_DOMAINS}/build/test_mods/msr_autogen"
BOOT_KO="${MSR_AUTOGEN_BUILD_DIR}/boot/lcd_test_mod_msr_autogen_boot.ko"
KLCD_KO="${MSR_AUTOGEN_BUILD_DIR}/msr_klcd/lcd_test_mod_msr_autogen_msr_klcd.ko"
LCD_KO="${MSR_AUTOGEN_BUILD_DIR}/msr_lcd/lcd_test_mod_msr_autogen_msr_lcd.ko"

IDLC_BIN="${BASE_DIR}/lcds-idl/build/idlc"

generate_idl() {
	pushd ${MSR_BC}
	sudo ../../run_nescheck.sh msr
	# Yeah I know
	sleep 60
	popd
}

autogen_module() {
	pushd ${TEST_MODS}
	cp -a ${MSR_BOILERPLATE} .
	pushd msr_autogen
	cp ${MSR_BC}/kernel.idl msr_autogen.idl
	patch -p0 < ${MSR_ARTIFACT}/msr-idl-changes.patch
	${IDLC_BIN} ./msr_autogen.idl	
	popd
	popd
}

prepare_module() {
	pushd ${TEST_MODS}
	rm -f ${TEST_MODS}/config
	DEFCONFIG="${LVD_DOMAINS}/scripts/defaultconfig"
	echo "msr_autogen/boot nonisolated" >> ${DEFCONFIG}
	echo "msr_autogen/msr_lcd isolated" >> ${DEFCONFIG}
	echo "msr_autogen/msr_klcd nonisolated" >> ${DEFCONFIG}

	echo "obj-m += msr_autogen/" >> "${LVD_DOMAINS}/scripts/Kbuild.test_mods"

	patch -p0 < "${MSR_ARTIFACT}/msr-driver-changes.patch"
	popd
}

build_module() {
	pushd ${LVD_DOMAINS}
	make

	if [[ ! -n ${BOOT_KO} ]] || [[ ! -n ${KLCD_KO} ]] || [[ ! -n ${LCD_KO} ]];then 
		echo "Building autogenerated module failed"
	else
		echo "Module successfully built"
	fi
	popd
}

load_bflank_module() {
	sudo ${MSR_ARTIFACT}/toggle_ht.sh off
	pushd "${BFLANK_BUILD}"
	make driver_quick && make quick
	popd
}

load_module() {
	load_bflank_module;
	pushd ${LVD_DOMAINS}
	./scripts/mk
	sleep 5;
	./scripts/loadex msr_autogen
	# allow some time for the module to get loaded
	sleep 120;
	popd
}

test_module() {
	if ! [ -x "$(command -v rdmsr)" ]; then
		echo "Installing msr-tools ..."
		sudo apt update
		sudo apt install -y msr-tools
	fi
	RDMSR_BIN=$(which rdmsr)
	WRMSR_BIN=$(which wrmsr)

	sudo ${RDMSR_BIN} 0x1a4
	sudo ${WRMSR_BIN} 0x1a4 0xf
	READ_BACK=$(sudo ${RDMSR_BIN} 0x1a4)

	if [[ ${READ_BACK} == "f" ]]; then
		echo "=====================================";
		echo "Autogenerated msr module test passed";
		echo "=====================================";
	else
		echo "Failed to readback the written value from msr";
	fi
}

generate_idl
autogen_module
prepare_module

build_module
load_module
test_module
